// This file was generated by counterfeiter
package fakes

import (
	"light-stemcell-builder/resources"
	"sync"
)

type FakeVolumeDriver struct {
	CreateStub        func(resources.VolumeDriverConfig) (resources.Volume, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 resources.VolumeDriverConfig
	}
	createReturns struct {
		result1 resources.Volume
		result2 error
	}
}

func (fake *FakeVolumeDriver) Create(arg1 resources.VolumeDriverConfig) (resources.Volume, error) {
	fake.createMutex.Lock()
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 resources.VolumeDriverConfig
	}{arg1})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub(arg1)
	} else {
		return fake.createReturns.result1, fake.createReturns.result2
	}
}

func (fake *FakeVolumeDriver) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeVolumeDriver) CreateArgsForCall(i int) resources.VolumeDriverConfig {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.createArgsForCall[i].arg1
}

func (fake *FakeVolumeDriver) CreateReturns(result1 resources.Volume, result2 error) {
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 resources.Volume
		result2 error
	}{result1, result2}
}

var _ resources.VolumeDriver = new(FakeVolumeDriver)
