// This file was generated by counterfeiter
package fakes

import (
	"light-stemcell-builder/resources"
	"sync"
)

type FakeAmiDriver struct {
	CreateStub        func(resources.AmiDriverConfig) (resources.Ami, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 resources.AmiDriverConfig
	}
	createReturns struct {
		result1 resources.Ami
		result2 error
	}
}

func (fake *FakeAmiDriver) Create(arg1 resources.AmiDriverConfig) (resources.Ami, error) {
	fake.createMutex.Lock()
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 resources.AmiDriverConfig
	}{arg1})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub(arg1)
	} else {
		return fake.createReturns.result1, fake.createReturns.result2
	}
}

func (fake *FakeAmiDriver) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeAmiDriver) CreateArgsForCall(i int) resources.AmiDriverConfig {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.createArgsForCall[i].arg1
}

func (fake *FakeAmiDriver) CreateReturns(result1 resources.Ami, result2 error) {
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 resources.Ami
		result2 error
	}{result1, result2}
}

var _ resources.AmiDriver = new(FakeAmiDriver)
