---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/golang-release

inputs:
- name: light-stemcell-builder

run:
  path: light-stemcell-builder/ci/tasks/test-unit.sh
