// This file was generated by counterfeiter
package fakes

import (
	"light-stemcell-builder/driverset"
	"light-stemcell-builder/resources"
	"sync"
)

type FakeIsolatedRegionDriverSet struct {
	MachineImageDriverStub        func() resources.MachineImageDriver
	machineImageDriverMutex       sync.RWMutex
	machineImageDriverArgsForCall []struct{}
	machineImageDriverReturns     struct {
		result1 resources.MachineImageDriver
	}
	VolumeDriverStub        func() resources.VolumeDriver
	volumeDriverMutex       sync.RWMutex
	volumeDriverArgsForCall []struct{}
	volumeDriverReturns     struct {
		result1 resources.VolumeDriver
	}
	CreateSnapshotDriverStub        func() resources.SnapshotDriver
	createSnapshotDriverMutex       sync.RWMutex
	createSnapshotDriverArgsForCall []struct{}
	createSnapshotDriverReturns     struct {
		result1 resources.SnapshotDriver
	}
	CreateAmiDriverStub        func() resources.AmiDriver
	createAmiDriverMutex       sync.RWMutex
	createAmiDriverArgsForCall []struct{}
	createAmiDriverReturns     struct {
		result1 resources.AmiDriver
	}
}

func (fake *FakeIsolatedRegionDriverSet) MachineImageDriver() resources.MachineImageDriver {
	fake.machineImageDriverMutex.Lock()
	fake.machineImageDriverArgsForCall = append(fake.machineImageDriverArgsForCall, struct{}{})
	fake.machineImageDriverMutex.Unlock()
	if fake.MachineImageDriverStub != nil {
		return fake.MachineImageDriverStub()
	} else {
		return fake.machineImageDriverReturns.result1
	}
}

func (fake *FakeIsolatedRegionDriverSet) MachineImageDriverCallCount() int {
	fake.machineImageDriverMutex.RLock()
	defer fake.machineImageDriverMutex.RUnlock()
	return len(fake.machineImageDriverArgsForCall)
}

func (fake *FakeIsolatedRegionDriverSet) MachineImageDriverReturns(result1 resources.MachineImageDriver) {
	fake.MachineImageDriverStub = nil
	fake.machineImageDriverReturns = struct {
		result1 resources.MachineImageDriver
	}{result1}
}

func (fake *FakeIsolatedRegionDriverSet) VolumeDriver() resources.VolumeDriver {
	fake.volumeDriverMutex.Lock()
	fake.volumeDriverArgsForCall = append(fake.volumeDriverArgsForCall, struct{}{})
	fake.volumeDriverMutex.Unlock()
	if fake.VolumeDriverStub != nil {
		return fake.VolumeDriverStub()
	} else {
		return fake.volumeDriverReturns.result1
	}
}

func (fake *FakeIsolatedRegionDriverSet) VolumeDriverCallCount() int {
	fake.volumeDriverMutex.RLock()
	defer fake.volumeDriverMutex.RUnlock()
	return len(fake.volumeDriverArgsForCall)
}

func (fake *FakeIsolatedRegionDriverSet) VolumeDriverReturns(result1 resources.VolumeDriver) {
	fake.VolumeDriverStub = nil
	fake.volumeDriverReturns = struct {
		result1 resources.VolumeDriver
	}{result1}
}

func (fake *FakeIsolatedRegionDriverSet) CreateSnapshotDriver() resources.SnapshotDriver {
	fake.createSnapshotDriverMutex.Lock()
	fake.createSnapshotDriverArgsForCall = append(fake.createSnapshotDriverArgsForCall, struct{}{})
	fake.createSnapshotDriverMutex.Unlock()
	if fake.CreateSnapshotDriverStub != nil {
		return fake.CreateSnapshotDriverStub()
	} else {
		return fake.createSnapshotDriverReturns.result1
	}
}

func (fake *FakeIsolatedRegionDriverSet) CreateSnapshotDriverCallCount() int {
	fake.createSnapshotDriverMutex.RLock()
	defer fake.createSnapshotDriverMutex.RUnlock()
	return len(fake.createSnapshotDriverArgsForCall)
}

func (fake *FakeIsolatedRegionDriverSet) CreateSnapshotDriverReturns(result1 resources.SnapshotDriver) {
	fake.CreateSnapshotDriverStub = nil
	fake.createSnapshotDriverReturns = struct {
		result1 resources.SnapshotDriver
	}{result1}
}

func (fake *FakeIsolatedRegionDriverSet) CreateAmiDriver() resources.AmiDriver {
	fake.createAmiDriverMutex.Lock()
	fake.createAmiDriverArgsForCall = append(fake.createAmiDriverArgsForCall, struct{}{})
	fake.createAmiDriverMutex.Unlock()
	if fake.CreateAmiDriverStub != nil {
		return fake.CreateAmiDriverStub()
	} else {
		return fake.createAmiDriverReturns.result1
	}
}

func (fake *FakeIsolatedRegionDriverSet) CreateAmiDriverCallCount() int {
	fake.createAmiDriverMutex.RLock()
	defer fake.createAmiDriverMutex.RUnlock()
	return len(fake.createAmiDriverArgsForCall)
}

func (fake *FakeIsolatedRegionDriverSet) CreateAmiDriverReturns(result1 resources.AmiDriver) {
	fake.CreateAmiDriverStub = nil
	fake.createAmiDriverReturns = struct {
		result1 resources.AmiDriver
	}{result1}
}

var _ driverset.IsolatedRegionDriverSet = new(FakeIsolatedRegionDriverSet)
