// This file was generated by counterfeiter
package fakes

import (
	"light-stemcell-builder/driverset"
	"light-stemcell-builder/resources"
	"sync"
)

type FakeIsolatedRegionDriverSet struct {
	CreateMachineImageDriverStub        func() resources.MachineImageDriver
	createMachineImageDriverMutex       sync.RWMutex
	createMachineImageDriverArgsForCall []struct{}
	createMachineImageDriverReturns     struct {
		result1 resources.MachineImageDriver
	}
	CreateVolumeDriverStub        func() resources.VolumeDriver
	createVolumeDriverMutex       sync.RWMutex
	createVolumeDriverArgsForCall []struct{}
	createVolumeDriverReturns     struct {
		result1 resources.VolumeDriver
	}
	CreateSnapshotDriverStub        func() resources.SnapshotDriver
	createSnapshotDriverMutex       sync.RWMutex
	createSnapshotDriverArgsForCall []struct{}
	createSnapshotDriverReturns     struct {
		result1 resources.SnapshotDriver
	}
	CreateAmiDriverStub        func() resources.AmiDriver
	createAmiDriverMutex       sync.RWMutex
	createAmiDriverArgsForCall []struct{}
	createAmiDriverReturns     struct {
		result1 resources.AmiDriver
	}
}

func (fake *FakeIsolatedRegionDriverSet) CreateMachineImageDriver() resources.MachineImageDriver {
	fake.createMachineImageDriverMutex.Lock()
	fake.createMachineImageDriverArgsForCall = append(fake.createMachineImageDriverArgsForCall, struct{}{})
	fake.createMachineImageDriverMutex.Unlock()
	if fake.CreateMachineImageDriverStub != nil {
		return fake.CreateMachineImageDriverStub()
	} else {
		return fake.createMachineImageDriverReturns.result1
	}
}

func (fake *FakeIsolatedRegionDriverSet) CreateMachineImageDriverCallCount() int {
	fake.createMachineImageDriverMutex.RLock()
	defer fake.createMachineImageDriverMutex.RUnlock()
	return len(fake.createMachineImageDriverArgsForCall)
}

func (fake *FakeIsolatedRegionDriverSet) CreateMachineImageDriverReturns(result1 resources.MachineImageDriver) {
	fake.CreateMachineImageDriverStub = nil
	fake.createMachineImageDriverReturns = struct {
		result1 resources.MachineImageDriver
	}{result1}
}

func (fake *FakeIsolatedRegionDriverSet) CreateVolumeDriver() resources.VolumeDriver {
	fake.createVolumeDriverMutex.Lock()
	fake.createVolumeDriverArgsForCall = append(fake.createVolumeDriverArgsForCall, struct{}{})
	fake.createVolumeDriverMutex.Unlock()
	if fake.CreateVolumeDriverStub != nil {
		return fake.CreateVolumeDriverStub()
	} else {
		return fake.createVolumeDriverReturns.result1
	}
}

func (fake *FakeIsolatedRegionDriverSet) CreateVolumeDriverCallCount() int {
	fake.createVolumeDriverMutex.RLock()
	defer fake.createVolumeDriverMutex.RUnlock()
	return len(fake.createVolumeDriverArgsForCall)
}

func (fake *FakeIsolatedRegionDriverSet) CreateVolumeDriverReturns(result1 resources.VolumeDriver) {
	fake.CreateVolumeDriverStub = nil
	fake.createVolumeDriverReturns = struct {
		result1 resources.VolumeDriver
	}{result1}
}

func (fake *FakeIsolatedRegionDriverSet) CreateSnapshotDriver() resources.SnapshotDriver {
	fake.createSnapshotDriverMutex.Lock()
	fake.createSnapshotDriverArgsForCall = append(fake.createSnapshotDriverArgsForCall, struct{}{})
	fake.createSnapshotDriverMutex.Unlock()
	if fake.CreateSnapshotDriverStub != nil {
		return fake.CreateSnapshotDriverStub()
	} else {
		return fake.createSnapshotDriverReturns.result1
	}
}

func (fake *FakeIsolatedRegionDriverSet) CreateSnapshotDriverCallCount() int {
	fake.createSnapshotDriverMutex.RLock()
	defer fake.createSnapshotDriverMutex.RUnlock()
	return len(fake.createSnapshotDriverArgsForCall)
}

func (fake *FakeIsolatedRegionDriverSet) CreateSnapshotDriverReturns(result1 resources.SnapshotDriver) {
	fake.CreateSnapshotDriverStub = nil
	fake.createSnapshotDriverReturns = struct {
		result1 resources.SnapshotDriver
	}{result1}
}

func (fake *FakeIsolatedRegionDriverSet) CreateAmiDriver() resources.AmiDriver {
	fake.createAmiDriverMutex.Lock()
	fake.createAmiDriverArgsForCall = append(fake.createAmiDriverArgsForCall, struct{}{})
	fake.createAmiDriverMutex.Unlock()
	if fake.CreateAmiDriverStub != nil {
		return fake.CreateAmiDriverStub()
	} else {
		return fake.createAmiDriverReturns.result1
	}
}

func (fake *FakeIsolatedRegionDriverSet) CreateAmiDriverCallCount() int {
	fake.createAmiDriverMutex.RLock()
	defer fake.createAmiDriverMutex.RUnlock()
	return len(fake.createAmiDriverArgsForCall)
}

func (fake *FakeIsolatedRegionDriverSet) CreateAmiDriverReturns(result1 resources.AmiDriver) {
	fake.CreateAmiDriverStub = nil
	fake.createAmiDriverReturns = struct {
		result1 resources.AmiDriver
	}{result1}
}

var _ driverset.IsolatedRegionDriverSet = new(FakeIsolatedRegionDriverSet)
