---
groups:
  - name: builder
    jobs:
      - test
      - promote

  - name: publishing
    jobs:
      - publish

  - name: versioning
    jobs:
      - bump-minor
      - bump-major
      - promote

jobs:
  - name: test
    serial: true
    plan:
      - get: builder-src
        resource: builder-src-in
        trigger: true
      - task: test
        file: builder-src/ci/tasks/test.yml
        config:
          params:
            access_key: {{test__access_key}}
            secret_key: {{test__secret_key}}
            bucket_name: {{test__bucket_name}}
            region: {{test__region}}
            ami_fixture_id: {{test__ami_fixture_id}}

  - name: promote
    plan:
      - aggregate:
        - get: builder-src
          passed: [test]
          resource: builder-src-in
          trigger: true
        - get: version-semver
          params: { bump: patch }
      # - put: version-semver
      #   params: { file: version-semver/number }
      # - put: builder-src-out
      #   params: { repository: builder-src }

  - name: publish
    serial: true
    plan:
      - get: builder-src
        resource: builder-src-out
        trigger: false
      - get: input-stemcell
        resource: ubuntu-input-stemcell
        trigger: false
      - task: build
        file: builder-src/ci/tasks/build.yml
        config:
          params:
            access_key: {{publish__access_key}}
            secret_key: {{publish__secret_key}}
            bucket_name: {{publish__bucket_name}}
            region: {{publish__region}}
            copy_dests: {{publish__copy_dests}}
            ami_description: {{publish__ami_description}}
            ami_is_public: {{publish__ami_is_public}}
            ami_virtualization_type: {{publish__ami_virtualization_type}}

      - put: ubuntu-light-stemcell
        params:
          from: light-stemcell/light-bosh-stemcell-(.*).tgz

  - name: bump-minor
    public: true
    plan:
      - get: version-semver
        params: { bump: minor }
      - put: version-semver
        params: { file: version-semver/number }

  - name: bump-major
    public: true
    plan:
      - get: version-semver
        params: { bump: major }
      - put: version-semver
        params: { file: version-semver/number }

resources:
  - name: builder-src-in
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/aws-light-stemcell-builder.git
      branch: cti/107775580
      private_key: {{builder__github_deployment_key}}

  - name: builder-src-out
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/aws-light-stemcell-builder.git
      branch: master
      private_key: {{builder__github_deployment_key}}

  - name: version-semver
    type: semver
    source:
      initial_version: 0.0.1
      key: current-version
      access_key_id: {{builder__access_key}}
      secret_access_key: {{builder__secret_key}}
      bucket: {{builder__bucket}}

  - name: ubuntu-input-stemcell
    type: s3
    source:
      regexp: bosh-stemcell-([0-9]+)-aws-xen-ubuntu-trusty-go_agent.tgz
      access_key_id: {{input__access_key}}
      secret_access_key: {{input__secret_key}}
      bucket: {{input__bucket}}

  - name: ubuntu-light-stemcell
    type: s3
    source:
      regexp: light-bosh-stemcell-([0-9]+)-aws-xen-hvm-ubuntu-trusty-go_agent.tgz
      access_key_id: {{publish__access_key}}
      secret_access_key: {{publish__secret_key}}
      bucket: {{light__bucket}}
