---
groups:
  - name: all-aws
    jobs:
      - test-unit
      - test-drivers
      - test-integration
      - bump-minor
      - bump-major
      - promote
      - publish-ubuntu-3421
      - publish-ubuntu-3445
      - publish-centos-3468
      - publish-ubuntu-3468
      - publish-ubuntu-3363
      - publish-ubuntu-3312
  - name: "3312"
    jobs:
      - publish-ubuntu-3312
  - name: "3363"
    jobs:
      - publish-ubuntu-3363
  - name: "3421"
    jobs:
      - publish-ubuntu-3421
  - name: "3445"
    jobs:
      - publish-ubuntu-3445
  - name: "3468"
    jobs:
      - publish-centos-3468
      - publish-ubuntu-3468
  - name: alpha
    jobs:
      - publish-centos-alpha
      - publish-ubuntu-alpha

shared:
  - &get-china-stemcell
    get: cn-input-stemcell
    version: every
    tags: [asia]
    trigger: true
    params:
      preserve_filename: true
  - &get-us_gov-stemcell
    get: us_gov-input-stemcell
    version: every
    trigger: true
    params:
      preserve_filename: true
  - &get-us-stemcell
    get: us-input-stemcell
    version: every
    trigger: true
    params:
      preserve_filename: true
  - &get-china-builder-src
    get: cn-builder-src
    tags: [asia]
    resource: builder-src-out
  - &get-us_gov-builder-src
    get: us_gov-builder-src
    resource: builder-src-out
  - &get-us-builder-src
    get: us-builder-src
    resource: builder-src-out
  - &build-china-stemcell-task
    task: build-china-stemcell
    file: cn-builder-src/ci/tasks/build.yml
    tags: [asia]
    input_mapping:
      input-stemcell: cn-input-stemcell
      builder-src: cn-builder-src
    output_mapping: {light-stemcell: cn-light-stemcell}
    params:
      ami_description: {{publish__ami_description}}
      ami_encrypted: {{publish__ami_encrypted}}
      ami_kms_key_id: {{publish__ami_kms_key_id}}
      ami_visibility: {{publish__ami_visibility}}
      ami_region: {{publish__cn_region}}
      ami_access_key: {{publish__cn_access_key}}
      ami_secret_key: {{publish__cn_secret_key}}
      ami_bucket_name: {{publish__cn_bucket}}
      ami_server_side_encryption: {{publish__cn_server_side_encryption}}
      ami_destinations: []
      ami_virtualization_type: hvm
  - &build-us_gov-stemcell-task
    task: build-us_gov-stemcell
    file: us_gov-builder-src/ci/tasks/build.yml
    input_mapping:
      input-stemcell: us_gov-input-stemcell
      builder-src: us_gov-builder-src
    output_mapping: {light-stemcell: us_gov-light-stemcell}
    params:
      ami_description: {{publish__ami_description}}
      ami_encrypted: {{publish__ami_encrypted}}
      ami_kms_key_id: {{publish__ami_kms_key_id}}
      ami_visibility: {{publish__ami_visibility}}
      ami_region: {{publish__us-gov_region}}
      ami_access_key: {{publish__us-gov_access_key}}
      ami_secret_key: {{publish__us-gov_secret_key}}
      ami_bucket_name: {{publish__us-gov_bucket}}
      ami_server_side_encryption: {{publish__us-gov_server_side_encryption}}
      ami_destinations: []
      ami_virtualization_type: hvm
  - &build-us-stemcell-task
    task: build-us-stemcell
    file: us-builder-src/ci/tasks/build.yml
    input_mapping:
      input-stemcell: us-input-stemcell
      builder-src: us-builder-src
    output_mapping: {light-stemcell: us-light-stemcell}
    params:
      ami_description: {{publish__ami_description}}
      ami_encrypted: {{publish__ami_encrypted}}
      ami_kms_key_id: {{publish__ami_kms_key_id}}
      ami_visibility: {{publish__ami_visibility}}
      ami_region: {{publish__us_region}}
      ami_access_key: {{publish__us_access_key}}
      ami_secret_key: {{publish__us_secret_key}}
      ami_bucket_name: {{publish__us_bucket}}
      ami_server_side_encryption: {{publish__us_server_side_encryption}}
      ami_virtualization_type: hvm
  - &build-alpha-stemcell-task
    task: build-us-stemcell
    file: us-builder-src/ci/tasks/build.yml
    input_mapping:
      input-stemcell: us-input-stemcell
      builder-src: us-builder-src
    params:
      ami_description: {{publish_alpha__ami_description}}
      ami_encrypted: {{publish_alpha__ami_encrypted}}
      ami_kms_key_id: {{publish_alpha__ami_kms_key_id}}
      ami_visibility: {{publish_alpha__ami_visibility}}
      ami_region: {{publish_alpha__us_region}}
      ami_access_key: {{publish_alpha__us_access_key}}
      ami_secret_key: {{publish_alpha__us_secret_key}}
      ami_bucket_name: {{publish_alpha__us_bucket}}
      ami_server_side_encryption: {{publish_alpha__us_server_side_encryption}}
      ami_virtualization_type: hvm
  - &merge-builds-task
    task: merge-builds
    file: us-builder-src/ci/tasks/merge-builds.yml
    input_mapping:
      builder-src: us-builder-src
  - &us_gov-merge-builds-task
    task: merge-builds
    file: us-builder-src/ci/tasks/us_gov-merge-builds.yml
    input_mapping:
      builder-src: us-builder-src
  - &publish-stemcell-and-checksum
    task: publish-stemcell-and-checksum
    file: us-builder-src/ci/tasks/publish-stemcell-and-checksum.yml
    input_mapping:
      builder-src: us-builder-src
    params:
      AWS_ACCESS_KEY_ID: {{output__bucket_access_key}}
      AWS_SECRET_ACCESS_KEY: {{output__bucket_secret_key}}
      AWS_DEFAULT_REGION: {{output__region}}
      OUTPUT_BUCKET: {{output__bucket}}
  - &publish-alpha-stemcell
    task: publish-alpha-stemcell
    file: us-builder-src/ci/tasks/publish-stemcell-and-checksum.yml
    input_mapping:
      builder-src: us-builder-src
    params:
      AWS_ACCESS_KEY_ID: {{alpha_output__bucket_access_key}}
      AWS_SECRET_ACCESS_KEY: {{alpha_output__bucket_secret_key}}
      AWS_DEFAULT_REGION: {{alpha_output__region}}
      OUTPUT_BUCKET: {{alpha_output__bucket}}

  - &publish-dev-test-stemcell-and-checksum
    task: publish-dev-test-stemcell-and-checksum
    file: us-builder-src/ci/tasks/publish-stemcell-and-checksum.yml
    input_mapping:
      builder-src: us-builder-src
    params:
      AWS_ACCESS_KEY_ID: {{dev_test_output__bucket_access_key}}
      AWS_SECRET_ACCESS_KEY: {{dev_test_output__bucket_secret_key}}
      AWS_DEFAULT_REGION: {{dev_test_output__region}}
      OUTPUT_BUCKET: {{dev_test_output__bucket}}

jobs:
  - name: test-unit
    serial: true
    plan:
      - get: builder-src
        resource: builder-src-in
        trigger: true
      - task: test
        file: builder-src/ci/tasks/test-unit.yml

  - name: test-drivers
    serial: true
    plan:
      - get: builder-src
        resource: builder-src-in
        trigger: true
      - task: test
        file: builder-src/ci/tasks/test-drivers.yml
        params:
          access_key:                 {{test__access_key}}
          secret_key:                 {{test__secret_key}}
          bucket_name:                {{test__bucket_name}}
          region:                     {{test__region}}
          copy_region:                {{test__copy_region}}
          ami_fixture_id:             {{test__ami_fixture_id}}
          kms_key_id:                 {{test__kms_key_id}}
          existing_volume_id:         {{test__volume_fixture_id}}
          existing_snapshot_id:       {{test__snapshot_fixture_id}}
          uploaded_machine_image_url: {{test__machine_image_fixture_url}}

  - name: test-integration
    serial: true
    plan:
      - get: builder-src
        resource: builder-src-in
        trigger: true
      - task: test
        file: builder-src/ci/tasks/test-integration.yml
        params:
          access_key:                 {{test__access_key}}
          secret_key:                 {{test__secret_key}}
          bucket_name:                {{test__bucket_name}}
          region:                     {{test__region}}
          copy_region:                {{test__copy_region}}
          cn_access_key:              {{test__cn_access_key}}
          cn_secret_key:              {{test__cn_secret_key}}
          cn_bucket_name:             {{test__cn_bucket_name}}
          cn_region:                  {{test__cn_region}}

  - name: promote
    plan:
      - aggregate:
        - get: builder-src
          passed: [test-unit, test-drivers, test-integration]
          resource: builder-src-in
          trigger: true
        - get: version-semver
          params: { bump: patch }
      - put: version-semver
        params: { file: version-semver/number }
      - put: builder-src-out
        params: { repository: builder-src }

  - name: publish-ubuntu-3312
    serial: true
    plan:
      - aggregate:
        - do:
          - aggregate:
            - <<: *get-china-stemcell
              resource: ubuntu-stemcell-3312
            - *get-china-builder-src
          - *build-china-stemcell-task
        - do:
          - aggregate:
            - <<: *get-us-stemcell
              resource: ubuntu-stemcell-3312
            - *get-us-builder-src
          - *build-us-stemcell-task
      - *merge-builds-task
      - *publish-stemcell-and-checksum

  - name: publish-ubuntu-3363
    serial: true
    plan:
      - aggregate:
        - do:
          - aggregate:
            - <<: *get-china-stemcell
              resource: ubuntu-stemcell-3363
            - *get-china-builder-src
          - *build-china-stemcell-task
        - do:
          - aggregate:
            - <<: *get-us-stemcell
              resource: ubuntu-stemcell-3363
            - *get-us-builder-src
          - *build-us-stemcell-task
      - *merge-builds-task
      - *publish-stemcell-and-checksum

  - name: publish-ubuntu-3421
    serial: true
    plan:
      - aggregate:
        - do:
          - aggregate:
            - <<: *get-china-stemcell
              resource: ubuntu-stemcell-3421
            - *get-china-builder-src
          - *build-china-stemcell-task
        - do:
          - aggregate:
            - <<: *get-us_gov-stemcell
              resource: ubuntu-stemcell-3421
            - *get-us_gov-builder-src
          - *build-us_gov-stemcell-task
        - do:
          - aggregate:
            - <<: *get-us-stemcell
              resource: ubuntu-stemcell-3421
            - *get-us-builder-src
          - *build-us-stemcell-task
      - *us_gov-merge-builds-task
      - *publish-stemcell-and-checksum

  - name: publish-ubuntu-3445
    serial: true
    plan:
      - aggregate:
        - do:
          - aggregate:
            - <<: *get-china-stemcell
              resource: ubuntu-stemcell-3445
            - *get-china-builder-src
          - *build-china-stemcell-task
        - do:
          - aggregate:
            - <<: *get-us_gov-stemcell
              resource: ubuntu-stemcell-3445
            - *get-us_gov-builder-src
          - *build-us_gov-stemcell-task
        - do:
          - aggregate:
            - <<: *get-us-stemcell
              resource: ubuntu-stemcell-3445
            - *get-us-builder-src
          - *build-us-stemcell-task
      - *us_gov-merge-builds-task
      - *publish-stemcell-and-checksum

  - name: publish-ubuntu-3468
    serial: true
    plan:
      - aggregate:
        - do:
          - aggregate:
            - <<: *get-china-stemcell
              resource: ubuntu-stemcell-3468
            - *get-china-builder-src
          - *build-china-stemcell-task
        - do:
          - aggregate:
            - <<: *get-us_gov-stemcell
              resource: ubuntu-stemcell-3468
            - *get-us_gov-builder-src
          - *build-us_gov-stemcell-task
        - do:
          - aggregate:
            - <<: *get-us-stemcell
              resource: ubuntu-stemcell-3468
            - *get-us-builder-src
          - *build-us-stemcell-task
      - *us_gov-merge-builds-task
      - *publish-stemcell-and-checksum

  - name: publish-centos-3468
    serial: true
    plan:
      - aggregate:
        - do:
          - aggregate:
            - <<: *get-china-stemcell
              resource: centos-stemcell-3468
            - *get-china-builder-src
          - *build-china-stemcell-task
        - do:
          - aggregate:
            - <<: *get-us_gov-stemcell
              resource: centos-stemcell-3468
            - *get-us_gov-builder-src
          - *build-us_gov-stemcell-task
        - do:
          - aggregate:
            - <<: *get-us-stemcell
              resource: centos-stemcell-3468
            - *get-us-builder-src
          - *build-us-stemcell-task
      - *us_gov-merge-builds-task
      - *publish-stemcell-and-checksum

  - name: bump-minor
    public: true
    plan:
      - get: version-semver
        params: { bump: minor }
      - put: version-semver
        params: { file: version-semver/number }

  - name: bump-major
    public: true
    plan:
      - get: version-semver
        params: { bump: major }
      - put: version-semver
        params: { file: version-semver/number }

  - name: publish-ubuntu-alpha
    serial: true
    plan:
      - do:
        - aggregate:
          - <<: *get-us-stemcell
            resource: ubuntu-stemcell-alpha
          - *get-us-builder-src
        - *build-alpha-stemcell-task
      - *publish-alpha-stemcell

  - name: publish-centos-alpha
    serial: true
    plan:
      - do:
        - aggregate:
          - <<: *get-us-stemcell
            resource: centos-stemcell-alpha
          - *get-us-builder-src
        - *build-alpha-stemcell-task
      - *publish-alpha-stemcell

resources:
  - name: builder-src-in
    type: git
    source:
      uri: git@github.com:cloudfoundry/bosh-aws-light-stemcell-builder.git
      branch: develop
      private_key: {{builder__github_deployment_key}}

  - name: builder-src-out
    type: git
    source:
      uri: git@github.com:cloudfoundry/bosh-aws-light-stemcell-builder.git
      branch: master
      private_key: {{builder__github_deployment_key}}

  - name: version-semver
    type: semver
    source:
      initial_version: 0.0.1
      key: current-version
      access_key_id: {{builder__access_key}}
      secret_access_key: {{builder__secret_key}}
      bucket: {{builder__bucket}}
      region_name: {{builder__region}}

  - name: ubuntu-stemcell-3363
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      force_regular: true
      version_family: "3363"

  - name: ubuntu-stemcell-3312
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-ubuntu-trusty-go_agent
      force_regular: true
      version_family: "3312"

  - name: ubuntu-stemcell-3421
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      force_regular: true
      version_family: "3421"

  - name: ubuntu-stemcell-3445
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      force_regular: true
      version_family: "3445"

  - name: centos-stemcell-3468
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-centos-7-go_agent
      force_regular: true
      version_family: "3468"

  - name: ubuntu-stemcell-3468
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      force_regular: true
      version_family: "3468"

  - name: centos-stemcell-alpha
    type: s3
    source:
      bucket: bosh-core-stemcells-candidate
      regexp: aws/bosh-stemcell-(\d+)-aws-xen-hvm-centos-7-go_agent.tgz

  - name: ubuntu-stemcell-alpha
    type: s3
    source:
      bucket: bosh-core-stemcells-candidate
      regexp: aws/bosh-stemcell-(\d+)-aws-xen-hvm-ubuntu-trusty-go_agent.tgz
