---
groups:
  - name: light-stemcell-builder
    jobs:
      - test-unit
      - test-drivers
      - test-integration
      - bump-minor
      - bump-major
      - promote
      - publish-centos-hvm
      - publish-centos-pv
      - publish-ubuntu-hvm
      - publish-ubuntu-pv

shared:
  - &get-china-stemcell
    get: cn-input-stemcell
    version: every
    tags: [aws-cn]
    trigger: true
    params:
      preserve_filename: true
  - &get-us-stemcell
    get: us-input-stemcell
    version: every
    trigger: true
    params:
      preserve_filename: true
  - &get-china-builder-src
    get: cn-builder-src
    tags: [aws-cn]
    resource: builder-src-out
  - &get-us-builder-src
    get: us-builder-src
    resource: builder-src-out
  - &build-china-stemcell-task
    task: build-china-stemcell
    file: cn-builder-src/ci/tasks/build.yml
    tags: [aws-cn]
    input_mapping:
      input-stemcell: cn-input-stemcell
      builder-src: cn-builder-src
    output_mapping: {light-stemcell: cn-light-stemcell}
    params: &build-china-stemcell-params
      ami_description: {{publish__ami_description}}
      ami_visibility: {{publish__ami_visibility}}
      ami_region: {{publish__cn_region}}
      ami_access_key: {{publish__cn_access_key}}
      ami_secret_key: {{publish__cn_secret_key}}
      ami_bucket_name: {{publish__cn_bucket}}
      ami_destinations: []
  - &build-us-stemcell-task
    task: build-us-stemcell
    file: us-builder-src/ci/tasks/build.yml
    input_mapping:
      input-stemcell: us-input-stemcell
      builder-src: us-builder-src
    output_mapping: {light-stemcell: us-light-stemcell}
    params: &build-us-stemcell-params
      ami_description: {{publish__ami_description}}
      ami_visibility: {{publish__ami_visibility}}
      ami_region: {{publish__us_region}}
      ami_access_key: {{publish__us_access_key}}
      ami_secret_key: {{publish__us_secret_key}}
      ami_bucket_name: {{publish__us_bucket}}
      ami_destinations: {{publish__us_destinations}}
  - &merge-builds-task
    task: merge-builds
    attempts: 5
    file: us-builder-src/ci/tasks/merge-builds.yml
    input_mapping:
      builder-src: us-builder-src
  - &put-light-stemcell
    put: light-stemcell
    attempts: 5
    params:
      file: light-stemcell/light-bosh-stemcell-*.tgz

jobs:
  - name: test-unit
    serial: true
    plan:
      - get: builder-src
        resource: builder-src-in
        trigger: true
      - task: test
        file: builder-src/ci/tasks/test-unit.yml

  - name: test-drivers
    serial: true
    plan:
      - get: builder-src
        resource: builder-src-in
        trigger: true
      - task: test
        file: builder-src/ci/tasks/test-drivers.yml
        params:
          access_key:                 {{test__access_key}}
          secret_key:                 {{test__secret_key}}
          bucket_name:                {{test__bucket_name}}
          region:                     {{test__region}}
          copy_region:                {{test__copy_region}}
          ami_fixture_id:             {{test__ami_fixture_id}}
          existing_volume_id:         {{test__volume_fixture_id}}
          existing_snapshot_id:       {{test__snapshot_fixture_id}}
          uploaded_machine_image_url: {{test__machine_image_fixture_url}}

  - name: test-integration
    serial: true
    plan:
      - get: builder-src
        resource: builder-src-in
        trigger: true
      - task: test
        file: builder-src/ci/tasks/test-integration.yml
        params:
          access_key:                 {{test__access_key}}
          secret_key:                 {{test__secret_key}}
          bucket_name:                {{test__bucket_name}}
          region:                     {{test__region}}
          copy_region:                {{test__copy_region}}
          cn_access_key:              {{test__cn_access_key}}
          cn_secret_key:              {{test__cn_secret_key}}
          cn_bucket_name:             {{test__cn_bucket_name}}
          cn_region:                  {{test__cn_region}}

  - name: promote
    plan:
      - aggregate:
        - get: builder-src
          passed: [test-unit, test-drivers, test-integration]
          resource: builder-src-in
          trigger: true
        - get: version-semver
          params: { bump: patch }
      - put: version-semver
        params: { file: version-semver/number }
      - put: builder-src-out
        params: { repository: builder-src }

  - name: publish-ubuntu-hvm
    serial: true
    plan:
      - aggregate:
        - do:
          - aggregate:
            - <<: *get-china-stemcell
              resource: ubuntu-stemcell
            - *get-china-builder-src
            - get: every-4-hours
              trigger: true
          - <<: *build-china-stemcell-task
            params:
              <<: *build-china-stemcell-params
              ami_virtualization_type: hvm
          attempts: 5
        - do:
          - aggregate:
            - <<: *get-us-stemcell
              resource: ubuntu-stemcell
            - *get-us-builder-src
          - <<: *build-us-stemcell-task
            params:
              <<: *build-us-stemcell-params
              ami_virtualization_type: hvm
          attempts: 5
      - *merge-builds-task
      - *put-light-stemcell

  - name: publish-ubuntu-pv
    serial: true
    plan:
      - aggregate:
        - do:
          - aggregate:
            - <<: *get-china-stemcell
              resource: ubuntu-stemcell
            - *get-china-builder-src
            - get: every-4-hours
              trigger: true
          - <<: *build-china-stemcell-task
            params:
              <<: *build-china-stemcell-params
              ami_virtualization_type: paravirtual
          attempts: 5
        - do:
          - aggregate:
            - <<: *get-us-stemcell
              resource: ubuntu-stemcell
            - *get-us-builder-src
          - <<: *build-us-stemcell-task
            params:
              <<: *build-us-stemcell-params
              ami_virtualization_type: paravirtual
          attempts: 5
      - *merge-builds-task
      - *put-light-stemcell

  - name: publish-centos-hvm
    serial: true
    plan:
      - aggregate:
        - do:
          - aggregate:
            - <<: *get-china-stemcell
              resource: centos-stemcell
            - *get-china-builder-src
            - get: every-4-hours
              trigger: true
          - <<: *build-china-stemcell-task
            params:
              <<: *build-china-stemcell-params
              ami_virtualization_type: hvm
          attempts: 5
        - do:
          - aggregate:
            - <<: *get-us-stemcell
              resource: centos-stemcell
            - *get-us-builder-src
          - <<: *build-us-stemcell-task
            params:
              <<: *build-us-stemcell-params
              ami_virtualization_type: hvm
          attempts: 5
      - *merge-builds-task
      - *put-light-stemcell

  - name: publish-centos-pv
    serial: true
    plan:
      - aggregate:
        - do:
          - aggregate:
            - <<: *get-china-stemcell
              resource: centos-stemcell
            - *get-china-builder-src
            - get: every-4-hours
              trigger: true
          - <<: *build-china-stemcell-task
            params:
              <<: *build-china-stemcell-params
              ami_virtualization_type: paravirtual
          attempts: 5
        - do:
          - aggregate:
            - <<: *get-us-stemcell
              resource: centos-stemcell
            - *get-us-builder-src
          - <<: *build-us-stemcell-task
            params:
              <<: *build-us-stemcell-params
              ami_virtualization_type: paravirtual
          attempts: 5
      - *merge-builds-task
      - *put-light-stemcell

  - name: bump-minor
    public: true
    plan:
      - get: version-semver
        params: { bump: minor }
      - put: version-semver
        params: { file: version-semver/number }

  - name: bump-major
    public: true
    plan:
      - get: version-semver
        params: { bump: major }
      - put: version-semver
        params: { file: version-semver/number }

resource_types:
  # TODO: remove custom type after PR is merged
  # https://www.pivotaltracker.com/story/show/130877947
  - name: bosh-io-pr-force-regular
    type: docker-image
    source:
      repository: boshcpi/bosh-io-pr-force-regular

resources:
  - name: every-4-hours
    type: time
    source:
      interval: 4h

  - name: builder-src-in
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/aws-light-stemcell-builder.git
      branch: develop
      private_key: {{builder__github_deployment_key}}

  - name: builder-src-out
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/aws-light-stemcell-builder.git
      branch: master
      private_key: {{builder__github_deployment_key}}

  - name: version-semver
    type: semver
    source:
      initial_version: 0.0.1
      key: current-version
      access_key_id: {{builder__access_key}}
      secret_access_key: {{builder__secret_key}}
      bucket: {{builder__bucket}}
      region_name: {{builder__region}}

  - name: centos-stemcell
    type: bosh-io-pr-force-regular
    source:
      name: bosh-aws-xen-centos-7-go_agent
      force_regular: true

  - name: ubuntu-stemcell
    type: bosh-io-pr-force-regular
    source:
      name: bosh-aws-xen-ubuntu-trusty-go_agent
      force_regular: true

  - name: light-stemcell
    type: s3
    source:
      regexp: light-bosh-stemcell-([\d\.]+)-.*\.tgz
      access_key_id: {{output__bucket_access_key}}
      secret_access_key: {{output__bucket_secret_key}}
      bucket: {{output__bucket}}
      region_name: {{output__region}}
