---
jobs:
  - name: test-unit
    public: true
    plan:
      - get: light-stemcell-builder
        trigger: true
      - task: test-unit
        file: light-stemcell-builder/ci/tasks/test-unit.yml

  - name: bump-deps
    plan:
    - in_parallel:
      - get: light-stemcell-builder
      - get: golang-release
      - get: weekly
        trigger: true
    - task: bump-deps
      file: golang-release/ci/tasks/shared/bump-deps.yml
      input_mapping:
        input_repo: light-stemcell-builder
      output_mapping:
        output_repo: bumped-light-stemcell-builder
    - task: test-unit
      file: light-stemcell-builder/ci/tasks/test-unit.yml
      input_mapping:
        light-stemcell-builder: bumped-light-stemcell-builder
    - put: light-stemcell-builder
      params:
        repository: bumped-light-stemcell-builder
        rebase: true

resources:
  - name: light-stemcell-builder
    type: git
    source:
      uri: git@github.com:cloudfoundry/bosh-aws-light-stemcell-builder.git
      branch: master
      private_key: ((github_deploy_key_bosh-aws-light-stemcell-builder.private_key))

  - name: golang-release
    type: git
    source:
      uri: https://github.com/bosh-packages/golang-release.git

  - name: weekly
    type: time
    source:
      start: 3:00 -0700
      stop: 4:30 -0700
      days: [ Saturday ]
